// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZyphraTrades.Infrastructure.Persistence;

#nullable disable

namespace ZyphraTrades.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209023939_AddThemeAndDefaults")]
    partial class AddThemeAndDefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("ZyphraTrades.Domain.Entities.ChecklistRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChecklistRules", (string)null);
                });

            modelBuilder.Entity("ZyphraTrades.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AccountBalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AccountBalanceBefore")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BreakevenAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BreakevenPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChecklistScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChecklistTotal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Commission")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConfidenceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Confluence")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmotionAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmotionBefore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Fees")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossPnl")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImprovementCommitment")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBreakevenActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LessonLearned")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MarketCondition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MistakeNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetPnl")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PositionSize")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostTradeObservation")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ResultR")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RiskAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RiskR")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RiskRewardRatio")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenshotPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Session")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Setup")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Slippage")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("StopLoss")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Strategy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Swap")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TakeProfit")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timeframe")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("ZyphraTrades.Domain.Entities.TradeChecklistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChecklistRuleId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistRuleId");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeChecklistEntries", (string)null);
                });

            modelBuilder.Entity("ZyphraTrades.Domain.Entities.TradePartial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MovedToBreakeven")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentClosed")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RealizedPnl")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("TradePartials", (string)null);
                });

            modelBuilder.Entity("ZyphraTrades.Domain.Entities.TradeTimeframeAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Analysis")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenshotPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeTimeframeAnalyses", (string)null);
                });

            modelBuilder.Entity("ZyphraTrades.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DefaultAccountBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultContext")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultRiskPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultSetup")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultStrategy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeframesJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("ZyphraTrades.Domain.Entities.TradeChecklistEntry", b =>
                {
                    b.HasOne("ZyphraTrades.Domain.Entities.ChecklistRule", "ChecklistRule")
                        .WithMany()
                        .HasForeignKey("ChecklistRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZyphraTrades.Domain.Entities.Trade", "Trade")
                        .WithMany("ChecklistEntries")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistRule");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("ZyphraTrades.Domain.Entities.TradePartial", b =>
                {
                    b.HasOne("ZyphraTrades.Domain.Entities.Trade", "Trade")
                        .WithMany("Partials")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("ZyphraTrades.Domain.Entities.TradeTimeframeAnalysis", b =>
                {
                    b.HasOne("ZyphraTrades.Domain.Entities.Trade", "Trade")
                        .WithMany("TimeframeAnalyses")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("ZyphraTrades.Domain.Entities.Trade", b =>
                {
                    b.Navigation("ChecklistEntries");

                    b.Navigation("Partials");

                    b.Navigation("TimeframeAnalyses");
                });
#pragma warning restore 612, 618
        }
    }
}
